### PR TITLE
Bricking the device with long messages

### PR DESCRIPTION
**Pull request by syspart**
Hello Jürgen, I had a problem with long text messages. 
When sending more than 8192 bytes, the message(s) will be displayed, but after turning of it never starts again. So I lost 4 badges.
Greetings Klaus

### CODE REVIEW

**Comment by s-light** [comment]
eventually this comment on amazon (for the bluetooth version) is relevant?
https://www.amazon.com/gp/customer-reviews/R2T15E1JHCX1GP/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&ASIN=B07P5X28JY
could be that it is possible to debrick with the windows-software?!
just an idea!

**Comment by syspart** [comment]
Yes I tried, but the device have not been found.

**Comment by s-light** [comment]
oh that is not good...
so it does not register as usb device anymore?

@jnweiger i think the we can merge this. ok?

wild guess: is it overwriting its own firmware? or only configuration parameter in the eeprom?

just out of curiosity - are you willing to open up one of the bricked ones and make a photo of the pcb?
i have started an [research.md](research.md) file..
we could add this there..
and currently we don't know what controller is in the 44x11 types..

**Comment by syspart** [comment]
I have a picture. How do I upload it?

**Comment by syspart** [comment]
Thi is the picture of the 44x11.
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by jnweiger** [comment]
@syspart you can drag/drop pictures into a comment here. Possibly zip the file before upload, if that makes things easier.

**Comment by syspart** [comment]
94f2b108-40ea-4230-954d-8bb108963589

**Comment by s-light** [comment]
thanks!
i have added this info to the [research.md](research.md#controller) file.
its a 
MindMotion MM32L062PF  
ARM Cortex-M0 48MHz  
64KB Flash, 8KB RAM, 39 IO, LQFP48  
that means is has dopple the Flash and Ram as the 12x48 badge from jnweiger.
so seams the did there first product with a bigger chip and then for the *newer one* (with more pixels)
they downsized the chip...

**Comment by lanrat** [comment]
FYI I have a few of these badges I've been playing with. The VBLab Bluetooth badge linked above that uses the BMP Badge software is different hardware & software from the badges manufactured by [shenzhen lesun electronics co. ltd](https://lesun-led.en.alibaba.com/) that are compatible with this library.

The Amazon reseller [Coolbird](https://amazon.com/gp/product/B07RX59KC1/) sells a bluetooth variant that is compatible with this library and a few others. It also includes software that may be able to reflash the firmware. I have a copy if you need it.

Unrelated but possibly of use: The installer for the software that came with my Coolbird badge also included a few of the Visual Basic source files for building their software...

**Pull request merged**
