### PR TITLE
Detecting changed messages

### PR DESCRIPTION
**Pull request by syspart**
With adding date&time to the header, the device knows a newer message has been send. 
So you don't have to remove the device when sending a new message.

### CODE REVIEW

**Comment by s-light** [comment]
where did you get the meanings for the fields from?
are there any resource i don't know of? ;-)

**Comment by syspart** [comment]
I took a close look at the .led file. 
You get it with the profesional windows badge program. The button with the usb sign on starts the export of the data.

Am 17. Juli 2019 22:13:23 MESZ schrieb "Stefan Krüger" <notifications@github.com>:
>where did you get the meanings for the fields from?
>are there any resource i don't know of? ;-)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jnweiger/led-name-badge-ls32/pull/16#issuecomment-512550637

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by jnweiger** [comment]
Nice reverse engineering. Thanks!

I have to try that! It sounds like it could solve #10 ?

**Comment by syspart** [comment]
If you send a message to the badge twice, it looks like something has happend. But nothing changed and the old messages are shown.

**Comment by jnweiger** [comment]
The exact conditions when a new message would *not* appear without this fix, are still unclear to me. Merging, it seems to make sense anyway.

**Pull request merged**
